name: Build autocore

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libncurses5-dev zlib1g-dev gawk git ccache gettext libssl-dev xsltproc wget unzip python3

    - name: Download OpenWrt SDK
      run: |
        wget https://downloads.openwrt.org/releases/21.02.3/targets/x86/64/openwrt-sdk-21.02.3-x86-64_gcc-8.4.0_musl.Linux-x86_64.tar.xz
        tar -xJf openwrt-sdk-21.02.3-x86-64_gcc-8.4.0_musl.Linux-x86_64.tar.xz
        mv openwrt-sdk-21.02.3-x86-64_gcc-8.4.0_musl.Linux-x86_64 openwrt-sdk

    - name: Update and install feeds
      run: |
        cd openwrt-sdk
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Clone luci-theme-argon
      run: |
        cd openwrt-sdk/package
        git clone https://github.com/sbwml/autocore-arm -b openwrt-23.05 autocore-arm

    - name: Configure build
      run: |
        cd openwrt-sdk
        make defconfig
        # Select the package LuCI -> Applications -> luci-app-tinyfilemanager
        echo "CONFIG_PACKAGE_autocore-x86=y" >> .config
        make defconfig

    - name: Compile autocore-arm
      run: |
        cd openwrt-sdk
        make package/autocore-arm/compile V=99

    - name: List compiled files
      run: |
        cd openwrt-sdk
        find bin -name "*.ipk"

    - name: Upload IPK package
      uses: actions/upload-artifact@v3
      with:
        name: autocore-arm
        path: |
          openwrt-sdk/bin/packages/**/luci-theme-argon_*.ipk

    - name: Zip packages
      run: |
        echo -e "testing" >> release.txt

    - name: Upload packages
      uses: ncipollo/release-action@main
      with:
        token: ${{ secrets.RELEASES_TOKEN }}
        artifacts: "openwrt-sdk/bin/packages/**/luci-theme-argon_*.ipk"
        allowUpdates: true
        replacesArtifacts: true
        bodyFile: "release.txt"
        tag: "x86"
